language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "iojs"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_script:
  - npm run coveralls
